### PR TITLE
CI: added build CI with caching and flake lock update action

### PR DESCRIPTION
**Pull request by Mast3rwaf1z**

### CODE REVIEW

**Review by mads256h — APPROVED** [review]
Clean pr can't test the update functionality but it should work.

**Comment by mads256h** [comment]
Squash and merge this bad boi

**Review by mads256h — CHANGES_REQUESTED** [review]
`main` -> `master` otherwise lgtm

**Comment by Mast3rwaf1z** [comment]
> `main` -> `master` otherwise lgtm

what? it is set to master?

**Comment by mads256h** [comment]
main -> master otherwise lgtm

> > `main` -> `master` otherwise lgtm
> 
> what? it is set to master?

yes

**Comment by Mast3rwaf1z** [comment]
why are you requesting changes then?

**Comment by mads256h** [comment]
Sorry it 

> why are you requesting changes then?
> 
> image

Sorry it looked like `main` when i reviewed

**Comment by Mast3rwaf1z** [comment]
i cannot merge without approval :)

**Comment by mads256h** [comment]
It is still not using a github actions matrix as per my review

**Comment by Mast3rwaf1z** [comment]
you didn't mention that in your review, and what do we need a matrix for? github actions doesn't support nixos and why would you want to test it on different ubuntu versions or macos when its only ever gonna run on nixos systems anyway?

unless you want the requested machine to be specified in the matrix (fastboy, oldboy)

**Review by mads256h — APPROVED** [review]

**Comment by mads256h** [comment]
Its just easier to add a new system and one system failing to build does not stop the rest of the systems from building

**Comment by Mast3rwaf1z** [comment]
> Its just easier to add a new system and one system failing to build does not stop the rest of the systems from building

Okay i couldn't see it in the initial review, maybe because you marked it stale before I read it?

**Pull request merged**
